<?php

$title = 'Add new todo';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('todo', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);

// Using formCollection
echo $this->formCollection($form);

// Echo each field explicitly
/*
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('description'));
echo $this->formSubmit($form->get('submit'));
*/
echo $this->form()->closeTag();
