<?php

$title = 'My todos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('todo', array('action'=>'add'));?>">Add new todo</a>
</p>

<table class="table">
<tr>
    <th>Description</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($todos as $todo) : ?>
<tr>
    <td><?php echo $this->escapeHtml($todo->description);?></td>
    <td>
        <a href="<?php echo $this->url('todo',
            array('action'=>'edit', 'id' => $todo->id));?>">Edit</a>
        <a href="<?php echo $this->url('todo',
            array('action'=>'delete', 'id' => $todo->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
